import type { GeneratedContent, ProductData } from "../../types";
import { amazonTheme as t } from "./theme";

function escapeHtml(value: string): string { return value.replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }

export function amazonCardHtml(product: ProductData, content: GeneratedContent, imageDataUrl: string): string {
  const titleSize = content.shortTitle.length > 75 ? 48 : content.shortTitle.length > 58 ? 55 : 64;
  const listPrice = product.amazon?.referencePriceType === "LIST_PRICE" ? product.oldPrice : undefined;
  const percentage = listPrice ? product.amazon?.savings?.percentage : undefined;
  const reference = listPrice ? `<span class="list-price"><span class="reference-label">List price </span><span class="old-price">${escapeHtml(listPrice.formatted)}</span></span>` : "";
  const savings = typeof percentage === "number" && Number.isInteger(percentage) && percentage > 0 && percentage <= 100
    ? `<span class="savings">${percentage}% off</span>` : "";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'; script-src 'unsafe-inline'"><meta name="viewport" content="width=${t.width}, initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;width:${t.width}px;height:${t.height}px;overflow:hidden;background:${t.background}}.card{position:relative;width:${t.width}px;height:${t.height}px;padding:54px 72px 64px;display:flex;flex-direction:column;background:${t.background};font-family:${t.bodyFont}}.accent{position:absolute;left:0;right:0;top:0;height:18px;background:${t.accent}}.store{height:54px;color:${t.ink};font-size:30px;font-weight:800;letter-spacing:3px;text-transform:uppercase}.image-area{height:710px;display:flex;align-items:center;justify-content:center;overflow:hidden}.image-area img{display:block;max-width:100%;max-height:100%;width:auto;height:auto;object-fit:contain}.title-area{height:220px;display:flex;align-items:center;justify-content:center;padding:8px 30px;overflow:hidden}.title{color:${t.ink};font-size:${titleSize}px;line-height:1.1;font-weight:750;text-align:center;overflow-wrap:anywhere;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden}.price-row{flex:1;min-height:0;display:flex;align-items:center;justify-content:center;gap:32px;white-space:nowrap;border-top:5px solid ${t.accent}}.deal-label{font-size:42px;letter-spacing:1px}.current-price{color:${t.dealRed};font-size:94px;font-weight:850;letter-spacing:-3px}.price-details{display:flex;flex-direction:column;align-items:flex-start;gap:8px}.list-price{color:${t.oldPriceGray};font-size:35px;font-weight:600}.old-price{text-decoration:line-through;text-decoration-thickness:3px}.savings{color:${t.dealRed};font-size:38px;font-weight:800}
</style></head><body><main class="card"><div class="accent"></div><div class="store">Amazon Deal</div><div class="image-area"><img src="${imageDataUrl}" alt="" loading="eager" decoding="sync"></div><div class="title-area"><div class="title">${escapeHtml(content.shortTitle)}</div></div><div class="price-row"><span class="current-price"><span class="deal-label">Now </span>${escapeHtml(product.currentPrice.formatted)}</span>${reference || savings ? `<span class="price-details">${reference}${savings}</span>` : ""}</div></main><script>const card=document.querySelector('.card'),image=document.querySelector('.image-area img');if(card&&image){const ready=()=>{if(image.naturalWidth>0&&image.naturalHeight>0)card.setAttribute('data-card-ready','true')};if(image.decode)image.decode().then(ready).catch(()=>{});else if(image.complete)ready();else image.addEventListener('load',ready,{once:true})}</script></body></html>`;
}
